name: Node.js Package Publish

on:
  push:
    branches: 
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18' # ここで使用するNode.jsのバージョンを指定

    - name: Install dependencies
      run: npm install

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: '${{secrets.NPM_TOKEN}}'
